const colors = {
  light: {
    text: "#ffffff",
    tint: "#EE4343",
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#161616",
    cardForeground: "#ffffff",
    primary: "#EE4343",
    primaryForeground: "#ffffff",
    secondary: "#272727",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#a6a6a6",
    accent: "#272727",
    accentForeground: "#ffffff",
    destructive: "#cc3333",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  dark: {
    text: "#ffffff",
    tint: "#EE4343",
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#161616",
    cardForeground: "#ffffff",
    primary: "#EE4343",
    primaryForeground: "#ffffff",
    secondary: "#272727",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#a6a6a6",
    accent: "#272727",
    accentForeground: "#ffffff",
    destructive: "#cc3333",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  radius: 8,
};

export default colors;
